application: ccsp-hw1
version: 1
runtime: python
api_version: 1

handlers:

# CSS/javascript
- url: /css
  static_dir: css
- url: /js
  static_dir: js

# Main Page
- url: /.*
  script: MainHandler.py
